src/RC.App.Client/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RC.Bll.Client.Services.Accounts;
using RC.Bll.Client.Models.Filter;

namespace RC.App.Client.Controllers
{
    public class AccountController : BaseController
    {
        private readonly IAccountService _accountService;

        public AccountController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        public async Task<IActionResult> Index()
        {
            var accounts = await _accountService.GetAll(new AccountFilter());

            return View(accounts);
        }

        public async Task<IActionResult> List(AccountFilter filter)
        {
            return PartialView("_List", await _accountService.GetAll(filter));
        }
    }
}

src/RC.App.Client/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace RC.App.Client.Controllers
{
    [Authorize]
    public class BaseController : Controller
    {
        public BaseController()
        {

        }

        public ViewComponentResult UnreadNotification()
        {
            return ViewComponent("UnreadNotification");
        }
    }
}

src/RC.App.Client/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using static RC.Bll.Common.Helpers.Constants;

namespace RC.App.Client.Controllers
{
    public class ErrorController : BaseController
    {
        [AllowAnonymous]
        [HttpGet("/error/{statusCode}")]
        public IActionResult ErrorRoute(string statusCode)
        {
            if (statusCode == "404")
            {
                return View(statusCode);
            }

            if (statusCode == "401" || statusCode == "302")
            {
                return View(statusCode);
            }

            if (statusCode == "500")
            {
                return View(statusCode);
            }

            return View("~/Views/Error/404.cshtml");
        }
    }
}

src/RC.App.Client/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RC.Bll.Client.Services.Authentication;
using Microsoft.AspNetCore.Authorization;
using RC.Bll.Client.Models.ViewModels;

namespace RC.App.Client.Controllers
{
    public class LoginController : BaseController
    {
        private readonly IRcAuthentication _authenticationService;

        public LoginController(IRcAuthentication authenticationService)
        {
            _authenticationService = authenticationService;
        }

        [AllowAnonymous]
        public IActionResult Index(string returnUrl)
        {
            if (this.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Account");
            }

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public virtual async Task<ActionResult> Index(LoginVm model)
        {
            var authResult = await _authenticationService.SignIn(model.Username, model.Password, model.RememberMe);

            if (!authResult.IsSuccess)
            {
                ViewData["LoginError"] = authResult.ErrorMessage;
                return View();
            }

            ViewData["LoginError"] = String.Empty;

            // If there's data about return url sent
            if (!String.IsNullOrEmpty(model.ReturnUrl))
                return Redirect(model.ReturnUrl);

            return RedirectToAction("Index", "Account");
        }

        [HttpGet]
        [Authorize]
        public virtual async Task<ActionResult> Logout(LoginVm model)
        {
            await _authenticationService.SignOut();
            return RedirectToAction("Index", "Login");
        }
    }
}

src/RC.App.Client/Controllers/MessageController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RC.Bll.Client.Models.ViewModels;
using RC.Bll.Client.Services.Messages;
using RC.Bll.Client.Models.Filter;
using System.Collections.Generic;
using System.Linq;

namespace RC.App.Client.Controllers
{
    public class MessageController : BaseController
    {
        private readonly IMessageService _messageService;

        public MessageController(IMessageService messageService)
        {
            _messageService = messageService;
        }

        public async Task<IActionResult> Index()
        {
            var messages = await _messageService.GetAll(await _messageService.InitializeFilterFormValues());
            return View(messages);
        }

        public async Task<IActionResult> List(MessageFilter filter)
        {
            return PartialView("_List", await _messageService.GetAll(filter));
        }

        [HttpGet]
        public IActionResult Send(Guid toAccountId)
        {
            return View(new MessageVm() { ToAccountId = toAccountId });
        }

        [HttpPost]
        public async Task<IActionResult> Send(MessageVm vieModel)
        {
            if (!ModelState.IsValid)
                return View(vieModel);

            await _messageService.Send(vieModel);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMessages(List<Guid> ids)
        {
            if (!ids.Any())
                return BadRequest();

            await _messageService.DeleteMessages(ids);
            return Ok();
        }
    }
}

src/RC.App.Client/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RC.Bll.Client.Models.ViewModels;
using RC.Bll.Client.Services.Accounts;

namespace RC.App.Client.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IAccountService _accountService;

        public RegisterController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        public IActionResult Index()
        {
            return View(new RegisterVm());
        }

        [HttpPost]
        public async Task<IActionResult> Index(RegisterVm model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var response = await _accountService.RegisterNew(model);
            if (!response.IsSuccess)
            {
                ViewData["RegisterError"] = response.ErrorMessage;
                return View();
            }

            return RedirectToAction("Index", "Login");
        }
    }
}

src/RC.App.Client/ViewComponents/UnreadNotificationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RC.Bll.Client.Services.Messages;
using System.Threading.Tasks;

namespace RC.App.Client.ViewComponents
{
    public class UnreadNotificationViewComponent : ViewComponent
    {
        private readonly IMessageService _messageService;

        public UnreadNotificationViewComponent(IMessageService messageService)
        {
            _messageService = messageService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var count = await _messageService.GetUnreadMessageCount();

            return View(count);
        }
    }
}

src/RC.App.Client/Views/Login/Index.cshtml
@model LoginVm
@using Microsoft.AspNetCore.Http;

@inject IHttpContextAccessor _httpContextAccessor;

@{
    ViewData["Title"] = "Login";
}

@{
    var redirectUrl = _httpContextAccessor.HttpContext.Request.Query["returnUrl"];
}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="card">
            <h1>@ViewBag.Title</h1>
            <section id="loginForm">
                <form asp-controller="Login" asp-action="Index" method="post" role="form" class="form-horizontal" autocomplete="off">

                    @Html.AntiForgeryToken()
                    <input type="hidden" asp-for="ReturnUrl" value="@redirectUrl" />
                    <h4>Enter your credentials</h4>
                    <hr />

                    <p class="text-danger">@ViewData["LoginError"]</p>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input asp-for="Username" class="form-control" placeholder="Username" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input asp-for="Password" class="form-control" placeholder="Password" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <div class="checkbox abc-checkbox abc-checkbox-default">
                                <input asp-for="RememberMe" type="checkbox" />
                                <label asp-for="RememberMe">Remember me</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="submit" value="Login" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>

src/RC.App.Client/Views/Message/Index.cshtml
@model MessagesVm

@{
    ViewData["Title"] = "Messages";
}

<div class="card">
    <div class="row">
        <div class="col-md-6">
            <h1>@ViewData["Title"]</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="">
                <form asp-action="List" role="form" id="filter-form" class="form-inline" method="post">
                    <input asp-for="Filter.Page" type="hidden" />
                    <input asp-for="Filter.IsFilterClicked" type="hidden" />
                    <label asp-for="Filter.WithAccountId" class="control-label">Show only with</label>
                    <select asp-for="Filter.WithAccountId" asp-items="@Model.Filter.AccountsDropdown" class="form-control autocomplete-dropdown">
                        <option value="">-- Select --</option>
                    </select>
                    <button type="submit" class="btn btn-primary">Show</button>
                    <a class="pull-right btn btn-danger btn-delete" data-action="@Url.Action("DeleteMessages")">Delete selected</a>
                    <a class="pull-right btn btn-default select-all">Select all</a>
                </form>
            </div>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="row">
                <div class="message-list-wrapper data-ajax">
                    @{
                        Html.RenderPartial("_List", Model);
                    }
                </div>
            </div>
        </div>
    </div>

</div>

src/RC.App.Client/Views/Message/Send.cshtml
@model MessageVm

@{
    ViewData["Title"] = "Send message";
}

<div class="card">
    <div class="row">
        <div class="col-md-6">
            <a asp-action="Index" asp-controller="Message" class="btn btn-default"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> See messagges </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1>@ViewData["Title"]</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Send" asp-controller="Message" role="form" class="form-horizontal" method="post">
                @{
                    Html.RenderPartial("_SendMessage");
                }
            </form>
        </div>
    </div>
</div>

src/RC.App.Client/Views/Message/_List.cshtml
@model MessagesVm

@inject ICurrentAccount CurrentAccount

@if (Model?.Messages != null && Model.Messages.Any())
{
    @foreach (var message in Model.Messages)
    {
        bool amITheSender = message.FromFullName == CurrentAccount.FullName;
        var messageClass = amITheSender ? "i-sender" : "h-sender col-md-offset-6";

        <div class="single-message-wrapper col-md-6 @messageClass">
            @{ string fromName = amITheSender ? "Me" : @message.FromFullName; }
            <div class="f-size-1-4">
                @if (amITheSender)
                {
                    <span>TO: </span> <b> @message.ToFullName </b>
                }
                else
                {
                    <span>FROM: </span> <b> @fromName </b>
                }
                <span class="pull-right">@Html.Raw($"{message.SentOn.ToShortDateString()} {message.SentOn.ToShortTimeString()}") </span>
                @if (!message.IsRead)
                {
                    <span class="label label-danger pull-right">New</span>
                }
                <br />
            </div>
            <br />
            <div class="f-size-1-7">
                <p><b> @message.Text </b> </p>
            </div>
            <div class="pull-left">
                <div class="checkbox abc-checkbox abc-checkbox-default">
                    <input type="checkbox" value="@message.Id" name="@message.Id" class="delete-checkbox" />
                    <label for="@message.Id"></label>
                </div>
            </div>
            @if (!amITheSender)
            {
                <div class="pull-right">
                    <a asp-action="Send" asp-controller="Message" asp-route-toAccountId="@message.FromAccountId" class="btn btn-default f-size-1-4">Reply to @message.FromFullName</a>
                </div>
            }
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
      }
}
else
{
   <div class="col-md-12 text-center text-danger p-t-d-40"> No messages </div>
}

@if (!Model.Filter.IsLastPage)
{
    <div class="load-more-parent">
        <a class="btn btn-primary btn-more">Load older</a>
    </div>
}
else if(Model.Filter.Page != 1 || Model.Messages.Any())
{
    <div class="text-center p-t-d-40">
        <span>No more messages</span>
    </div>
}

src/RC.App.Client/Views/Message/_SendMessage.cshtml
@model MessageVm

<div class="form-group">
    <input asp-for="ToAccountId" type="hidden"  />
    <div class="col-md-6">
        <label asp-for="Text" class="control-label">Text</label>
        <textarea asp-for="Text" class="form-control" rows="6" placeholder="Text"></textarea>
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <button type="submit" class="btn btn-primary">Send</button>
    </div>
</div>

src/RC.App.Client/Views/Register/Index.cshtml
@model RegisterVm


@{
    ViewData["Title"] = "Register";
}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="card">
            <h1>@ViewBag.Title</h1>
            <section id="loginForm">
                <form asp-controller="Register" asp-action="Index" method="post" role="form" class="form-horizontal" autocomplete="off">

                    @Html.AntiForgeryToken()
                    
                    <h4>Register new account</h4>
                    <hr />

                    <p class="text-danger">@ViewData["RegisterError"]</p>
                    <div class="form-group">
                        <div class="col-md-6">
                            <input asp-for="FirstName" class="form-control" placeholder="FirstName" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <input asp-for="LastName" class="form-control" placeholder="LastName" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input asp-for="Username" class="form-control" placeholder="Username" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input asp-for="Password" class="form-control" placeholder="Password" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="submit" value="Register" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>

src/RC.App.Client/Views/Shared/Components/UnreadNotification/Default.cshtml
@model int

<span class="badge"> @Model unread</span>

src/RC.App.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RC.App.Client</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://bootswatch.com/flatly/bootstrap.min.css"/>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/select2.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (this.User.Identity.IsAuthenticated)
                {
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RC.App.Client</a>
                }
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Index">Accounts</a></li>
                        <li>
                            <a asp-controller="Message" asp-action="Index">
                                
                                Messages <div class="notification-container" data-action="@Url.Action("UnreadNotification")">
                                    @await Component.InvokeAsync("UnreadNotification")
                                </div>
                            </a>
                        </li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - RC.App.Client</p>
        </footer>
    </div>

    @{
        Html.RenderPartial("_Loader");
    }

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/select2.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/RC.App.Client/Views/Shared/_Loader.cshtml
<div class="loader-wrapper hide">
    <div class="centerCF">
        <div class="loader">Loding...</div>
    </div>
</div>